export enum CollaborationType {
  CO_AUTHOR = 'CO_AUTHOR',
  TEAMMATE = 'TEAMMATE',
  SUPERVISOR_SEARCH = 'SUPERVISOR_SEARCH',
  RESEARCH_ASSISTANT = 'RESEARCH_ASSISTANT',
  THESIS_STUDENT_SEARCH = 'THESIS_STUDENT_SEARCH',
  DOMAIN_EXPERT = 'DOMAIN_EXPERT',
  DATA_COLLECTOR = 'DATA_COLLECTOR',
  RESEARCH_WRITER = 'RESEARCH_WRITER',
  STATISTICIAN = 'STATISTICIAN',
  OTHER = 'OTHER',
}
