export enum ResearchStage {
  IDEA = 'IDEA',
  LITERATURE_REVIEW = 'LITERATURE_REVIEW',
  DATA_COLLECTION = 'DATA_COLLECTION',
  IMPLEMENTATION = 'IMPLEMENTATION',
  EXPERIMENTATION = 'EXPERIMENTATION',
  PAPER_WRITING = 'PAPER_WRITING',
  SUBMISSION = 'SUBMISSION',
}
